"""init_db

Revision ID: 9b765318b90d
Revises: 
Create Date: 2026-10-01 19:17:03.596475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b765318b90d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.create_table('parcels',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Id of parcel'),
    sa.Column('pid', sa.Integer(), nullable=True, comment='parcel id'),
    sa.Column('address', sa.String(length=30), nullable=False),
    sa.Column('zone_code', sa.String(length=30), nullable=True, comment='zoning code'),
    sa.Column('land_desc', sa.String(length=30), nullable=True, comment='Description of land'),
    sa.Column('land_sf', sa.Float(), nullable=True, comment='Land Sf'),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When the user was first created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When the user was updated'),
    sa.Column('last_synced', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment="User's last login attempt"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('pid')
    )
    op.create_index(op.f('ix_parcels_id'), 'parcels', ['id'], unique=True)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index(op.f('ix_parcels_id'), table_name='parcels')
    op.drop_table('parcels')
    # ### end Alembic commands ###
